### ISSUE TITLE
Django statement and response are reversed

### ISSUE THREAD

**Issue by Issen007** [gunthercox/chatterbot-corpus#32] opened 2017-08-07 10:58 UTC
Hi,
I have create my on Corpus and successfully got the chatterbot successfully imported that data to Django so I can see that data under "admin -> Responds" 

But when I ask a question that is exact the same writing as the Corpus files I got a total different answer.
And if I remove that line from the database and ask the same question again I got a different answer but not the correct one.

Is there anything I do wrong here?

Thanks

**Comment by vkosuri** [comment] 2017-08-07 13:56
Similar issue https://github.com/gunthercox/ChatterBot/issues/902

**Comment by Issen007** [comment] 2017-08-07 14:24
The version we are running at the moment is 0.7.4

/Christian

**Comment by gunthercox** [comment] 2017-08-08 03:56
@Issen007 Thank you, I'm going to confirm this as a duplicate of https://github.com/gunthercox/ChatterBot/issues/902 and close it off. The defect is in the ChatterBot repository, not the corpus data. A fix for this will be released in a future version of the `chatterbot` module.

**Closed by gunthercox** 2017-08-08 03:56 UTC
